project:
  type: website

  preview: 
      port: 5555
      browser: true
      watch-inputs: true
      navigate: true
  
  resources:
    - "assets/**"
    - "etc/**"

# Metadata
pagetitle: "{{< meta title >}} | Aadam"
description-meta: "Aadam is a Ph.D. candidate at IUPUI, researching in the field of spatial transcriptomics."
author-meta: "Aadam"

freeze: true

# bibliography: files/bib/references.bib
# csl: files/bib/chicago-author-date.csl

website:
  title: "Aadam"
  description: "{{< meta description-meta >}}"
  favicon: "/assets/logo.png"
  site-url: "https://aadam.dev/"
  repo-url: "https://github.com/aadimator/aadam_dev"
  # repo-actions: issue
  image: /assets/logo.png

  google-analytics: 
    tracking-id: "UA-527449-5"
    anonymize-ip: true

  twitter-card: 
    image: "/files/profiles/twitter-card-large.png"
    description: "{{< meta description-meta >}}"
    card-style: summary_large_image
    creator: "@aadimator"
    site: "@aadimator"

  open-graph: 
    image: "/files/profiles/twitter-card-large.png"
    description: "{{< meta description-meta >}}"
    locale: en_US
  
  navbar:
    title: "Aadam"
    pinned: false
    right:
      - text: Blog
        href: blog/index.qmd
      - text: Research
        href: research/index.qmd

  # reader-mode: true

format:
  html:
    theme: _sass/panda.scss
    css: _sass/styles.css
    highlight-style: _sass/highlight-dark.theme
    smooth-scroll: true
    link-external-newwindow: true
    toc: false
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-block-border-left: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true



